### ISSUE TITLE
As an API, I want to provide comprehensive information about a single user to the front-end, so that the front-end can populate the user’s profile page

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#10]
Back-end story to provide user information to the client so that they can populate the user's profile page. Ensure's the GET method for a single user's profile functions and returns usable data.

Acceptance Criteria:
1. API calls for a single user returns all the data needed to populate the user's profile page.
2. Data is in format usable to client app.

**Comment by David-Egan** [comment]
Navigating to <domain name/localhost:portnumber>/profiles/<primary key>?format=json will retrieve the following JSON...
![openmicapiProfile.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592616af81cc6b00207eb4c2/125516c66e82c728ace21e0d46e7849f2d8f8aaa8ef9b673b652f69d2543653f6b14b1247a80e03cfd183954565d48ad44500e12fbffdc2ef2b63c77df5a0aead9680e66da2f53fde6d640e258f075c95d8fa4bf8b46c1ec342cee8b89463f1606188fed10.PNG)

**Comment by David-Egan** [comment]
More structured view of the data returned...
![opnemicProfilePrettified.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592616af81cc6b00207eb4c2/125516c66e82c728ace21e0d46e78494268f8aaabffbb045ad51f5a43b4333672002aa2e74c7af6aaf50740b0a0c0abe4b4a5a4dfeff882eaee76a778c090eb9d16d5821c03c16a4bdd30da313f871d51bdaebe5c01982fa3737e48a854e3a170c1189f85d35a69943ce4abb.PNG)
