### ISSUE TITLE
As a viewer, I want to be able to search for performances by title, so that I may find a specific performance

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#56]
Acceptance Criteria:
1. Performances can be searched for by title via an HTTP client.

**NOTE: This should function in the same manner as the existing functionality to search for users by username.

**Comment by David-Egan** [comment]
Add parameter "search" to search for performances by title.  This is a startsWith search. 
 Example: <rootURL>/profiles/?search=degan
