### ISSUE TITLE
Whe a show is flagged it should be visible in the flag database

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#64]
Create an endpoint in the API that adds a flag to a given performance. When a performance is flagged, it is added to the flagging table for performances.

Acceptance Criteria:
1. Performances that are flagged for the first time are added to the flagging module's data
2. If the performance is flagged again, increment the number of flags it has in the flagging module's data

**Comment by David-Egan** [comment]
Finished by @danieldrumma with commit 9e726ff
