### ISSUE TITLE
As a user, I want to have my search radius saved each time I change it so that I do not have to set my search radius for each search.

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#7]
Back-end story to ensure that search parameters for a user can be updated by the client

Acceptance Criteria:
1. Search parameters form client are successfully saved to logged-in user's account in back-end

**Comment by David-Egan** [comment]
Search Radius is a property of a user set to 100 (miles) by default.  It can be updated by sending JSON (see below) to the appropriate profiles url.

![searchrad.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/592616af81cc6b00207eb4c2/125516c66e82c728ace21e0d46fb919b31818bbb8eedfd0fe64de29b234324676b5ee17e29d7b579ea1a7a0758591ba915585f43a9ff882caeb36d62964e49bc8f3900299f7744eeaa880dbc00b0218e4f85b1ba8249c8ef3a2ce399c2.PNG)

**Comment by David-Egan** [comment]
Must add this to API document
