### ISSUE TITLE
As a performer, I would like to be able to add a rating on a 1-5 scale to a venue based on my experience with them.

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#79]
Acceptance Criteria:

1) Venues contain a field for a ratings that can be between 0.0 and 5.0
2) The Venues module contains an endpoint that allows performers to rate venues
3) A venue's rating is calculated by averaging all the ratings it has received.

**NOTES
- My idea for this is to add a "rating" model that has a rating value, the username of the rater, and the venue being rated. No rating can have have the same rater and venue (they are unique together) so that performers can only rate a venue once. It could be a good idea to make this it's own smaller module like comments.
- A performer is defined as anyone who does not have the genre "Fan" as their genre.

**Comment by David-Egan** [comment]
My current planned implementation doesn't store the average rating anywhere it needs to be calculated every time (which shouldn't be a problem performance-wise).  The alternative is to have performances and venues store their average rating and update for every review made for them.
