### ISSUE TITLE
As a user, I want to be able to use the search bar to search for users by username, so that I may find other users by username

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/user-stories#8]
Back-end story to implement main search functionality. API should return a list of users whose username either starts with or matches a string from the client. 

Acceptance Criteria:
1. Search returns a list of users that match or contains (starting from beginning) the provided search string by username.
2. Search results are returned in less than 2 seconds

**Comment by David-Egan** [comment]
URL: /profiles/?search=[Username]
Example: http://localhost:8000/profiles/?search=degan
